name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build with Maven
        run: mvn -DskipTests -B package --file pom.xml
      - name: Install http_server_spec dependencies
        run: |
          cd http_server_spec
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          cd ../
      - name: Testing with Maven
        run: mvn verify
